version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: dsp_postgres
    environment:
      POSTGRES_USER: dsp
      POSTGRES_PASSWORD: dsp_password
      POSTGRES_DB: dsp_db
    ports:
      - "5432:5432"
    volumes:
      - dsp_pgdata:/var/lib/postgresql/data
volumes:
  dsp_pgdata:
